RESOURCE_FILE_PATH = "resources"
CHAT_FILE_PATH = f"{RESOURCE_FILE_PATH}/chats.json"
CREDENTIALS_FILE_PATH = f"{RESOURCE_FILE_PATH}/credentials.json"
FORWARD_CONFIG_FILE_PATH = f"{RESOURCE_FILE_PATH}/forwardConfig.json"
HISTORY_FILE_PATH = f"{RESOURCE_FILE_PATH}/history.json"
IGNORE_CHATS_FILE_PATH = f"{RESOURCE_FILE_PATH}/ignoreChats.json"
WANTED_USER_FILE_PATH = f"{RESOURCE_FILE_PATH}/wantedUser.json"
AUTOPOST_CONFIG_FILE_PATH = f"{RESOURCE_FILE_PATH}/autopostConfig.json"

MEDIA_FOLDER_PATH = "media"
AUTOPOST_MEDIA_PATH = f"{MEDIA_FOLDER_PATH}/autopost"

SESSION_FOLDER_PATH = "sessions"
SESSION_PREFIX_PATH = f"{SESSION_FOLDER_PATH}/session_"
